server:
  port: 8001

spring:
  application:
    name: island-common-service
  profiles:
    active: dev
  main:
    banner-mode: 'OFF'
  jackson:
    serialization:
      indent-output: true
  swagger:
    basePackage: com.lkyl.island.common.service.controller
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

jvm_opts: -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx128m -Xmn64m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC


