spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  devtools:
    restart:
      enabled: false
  messages:
    encoding: UTF-8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    #    password: #zjmzxfzhl
    lettuce:
      pool:
        #最大连接数
        max-active: 1024
        #最大阻塞等待时间(负数表示无限制)
        max-wait: -1
        #最大空闲
        max-idle: 200
        #最小空闲
        min-idle: 10
      #sentinel:
      #master: mymaster
      #nodes: 168.168.168.101:26379,168.168.168.102:26379,168.168.168.103:26379
#  swagger:
#    authServerAddress: localhost:${server.port}/oauth/token
mybatis:
  mapperLocations: classpath:mapper/*.xml
#
ocean:
  datasource:
    username: root
    password: ENC(qGn7yGLPlYhFenLW3R6bqA==)
    url: jdbc:mysql://127.0.0.1:3306/iCommon?serverTimezone=GMT%2B8
    type: druid
    testOnBorrow: true
  httpclient:
    #defaultMaxPerRoute默认为2，maxTotal默认为20
    #连接池的最大连接数
    maxTotal: 300
    #每个route默认的最大连接数
    defaultMaxPerRoute: 100
    #建立连接超时
    connectTimeout: 1000000
    #等待连接超时
    connectionRequestTimeout: 5000000
    #从服务器读取超时
    socketTimeout: 100000000
    #连接状态验证
    staleConnectionCheckEnabled: true
    #validateAfterInactivity 空闲永久连接检查间隔，这个牵扯的还比较多
    #官方推荐使用这个来检查永久链接的可用性，而不推荐每次请求的时候才去检查
    validateAfterInactivity: 2000
    #  keyStorePath: C:/Users/Administrator/Desktop/广州办映射服务器测试证书20181010/dakehu/keystore.jks #证书路径
    #  keyStorePath: /usr/https_cert/keystore.jks #证书路径
    #  keyStorepass: 123456 #证书密码

    alwaysGenerateServicesFile: false
  security:
    oauth2:
      resourceId: frontend
      tokenStoreType: redis #inMemory 默认使用内存存储，#redis 使用redis存储
      publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDBHlQ8hiAAOku6QF2s3Hv/5lbv6dXSCATXEOXaVMri2W9Rr1gp+lTo46k+Iwh/RDiD5Z1fM6gorTivrPomoOkmeH1MhUwQaOJKsv7erzyLLxRo7lu4Xc8hHG5SlZa7ofIPl28cIyi6mOi9DLSxFYANV7uecSkVMvkuxDHJSSKjAQIDAQAB
      privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAOEsITHctTlSwELj+RbXptFwJJjfAZw1J0ejPWOSfqywN3po5RmzLWLmnWhvsCFb1hNvNrSOK6kVesg0FxjUIm/bPQzVF/AcXkZtNTosSgwk7espbg9N7/fBrhbX4emFS6ZCpr+GAks0p5PBVnoN2FXX3Hzb/rHzgzhDok8jFtD9AgMBAAECgYA4G1DiJcaaU/5ILJoCkRWmFjVoShkSnUP+W7SOPRCHYxlPzRdZAgaLID+UqE/Q4BtFmG6fKtXCOfHwNNqUezdhA/7r6+3hiaK949FtUemmzMeVdqA+FuXx0mXkEJqn8BiCyn5se7WC713ePY5YDbBwVOI9EAO0wGYsyTELR8a9GQJBAP4A5+Nzx2uviFCLUgCbPMZF5Ps0tARvG1kqxwfGUlJqnvjSUJoaChABtUvqg/QwNW0jvjpgNtNdMUq1Qnw9LmcCQQDi8TYMq8E7UppELfsOQhjK4c318w0a+XdJ0pDU/NMSY9IY7lDaASuW8xkxSCFuFWSG5j07bS53C6P37OKgG977AkBNPElGyHXjMMTqePK+bHXWdHpkSGpUztQqEO/kVVHC7djZIFqSAUj+BQbzxqPJJL+aKDw30/nX24aZiPRmgtQRAkEAvRAC3U+BbbCFQGOmEdzS1sKDWXEg6+YEkQXRDv+JwHpUn9x6kwQCkoD37eyPnSxJUXEidg2hdh/GfFdm/cf6XQJBAKEN/moacxZZJb0iPfau1I6vV27vlzVLfKTjXkz9K57Nd2euPND4sS+/NnlQjFsFV36FBTLSyFc1j4Fe9DooABQ=


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#数据库密码加密配置
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: BdaObXaELXX
    iv-generator-classname: org.jasypt.iv.NoIvGenerator	#设置初始向量IV生成器的类名

jvm_opts: -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx128m -Xmn64m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
