spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  messages:
    encoding: UTF-8
  datasource:
    username: root
    password: ENC(89KGKvlBqXXz/drQqhkgkw==)
    url: jdbc:mysql://127.0.0.1:3306/iCommon?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        #最大连接数
        max-active: 1024
        #最大阻塞等待时间(负数表示无限制)
        max-wait: -1
        #最大空闲
        max-idle: 200
        #最小空闲
        min-idle: 10
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
mybatis:
  mapperLocations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#数据库密码加密配置
# 加密配置
jasypt:
  encryptor:
    # 指定解密算法，需要和加密时使用的算法一致
    algorithm: PBEWithMD5AndDES
    # 指定initialization vector类型
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

snowflake:
  workerId: 1
  datacenterId: 2

ocean:
  security:
    oauth2:
      corsAllowedOrigins:
        - http://127.0.0.1
        - http://localhost