spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  messages:
    encoding: UTF-8
  datasource:
    username: wncommondb
    password: ENC(IcoQwH2iUtdF7F1y/nFOcOZs1o1FSBTrsY6HcQxU/d0=)
    url: ENC(/2QAK/J/5K8J39XRJDf0/0BIdxQEazIDCu2oVD9sNGwZxzUHXV/fngaazttBoT/qsxNv3M6VM2xvY1FTNVnlZXhwqRSp+Ms76IXKu80xK0s=)
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: ENC(XT0Ry88wLxrPl3ks/A++AJrTx1spd5xM)
    port: 6379
    password: ENC(OIOL4oDAEVTPAx1YzWMuXegdzLWJcoMg)
    lettuce:
      pool:
        #最大连接数
        max-active: 1024
        #最大阻塞等待时间(负数表示无限制)
        max-wait: -1
        #最大空闲
        max-idle: 200
        #最小空闲
        min-idle: 10
      #sentinel:
      #master: mymaster
      #nodes: 168.168.168.101:26379,168.168.168.102:26379,168.168.168.103:26379
#  swagger:
#    authServerAddress: localhost:${server.port}/oauth/token
mybatis:
  mapperLocations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#数据库密码加密配置
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator	#设置初始向量IV生成器的类名
snowflake:
  workerId: 1
  datacenterId: 2

ocean:
  security:
    oauth2:
      corsAllowedOrigins:
        - http://127.0.0.1