server:
  port: 8001
  servlet:
    context-path: /island/common

spring:
  application:
    name: island-common-service
  profiles:
    active: dev
  main:
    banner-mode: 'OFF'
  jackson:
    serialization:
      indent-output: true
  swagger:
    basePackage: com.lkyl.island.common.service.controller
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


